apiVersion: cleaner.cloudclub.dev/v1alpha1
kind: CleanPolicy
metadata:
  name: cleanpolicy-sample
  namespace: ukjang
spec:
  ttlHours: 24
  schedule: "1h"
  targetNamespaces:
    - ukjang
  jobSelector:
    matchLabels:
      cleanup: "true"