apiVersion: cleaner.cloudclub.dev/v1alpha1
kind: CleanPolicy
metadata:
  labels:
    app.kubernetes.io/name: project
    app.kubernetes.io/managed-by: kustomize
  name: cleanpolicy-sample
spec:
  # TODO(user): Add fields here
